language: swift
osx_image: xcode10

xcode_project: Alicerce.xcodeproj

before_install:
  - gem install cocoapods

install: true

cache:
  directories:
    - $HOME/Library/Caches/org.carthage.CarthageKit/dependencies
    - Carthage/Build

jobs:
  include:
    - stage: Build + Test
      env:
        - XCODE_WORKSPACE=Alicerce.xcworkspace
        - XCODE_PROJECT_NAME=Alicerce
        - XCODE_SDK=iphonesimulator
        - XCODE_ACTION='build test'
        - XCODE_DESTINATION='platform=iOS Simulator,name=iPhone 6s,OS=latest'
        - XCODE_DERIVED_DATA_PATH=build
        - XCODE_SCHEME=Alicerce
      before_script:
        - carthage checkout
      script:
        - set -o pipefail
        - xcodebuild $XCODE_ACTION -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -sdk "$XCODE_SDK" -destination "$XCODE_DESTINATION" -derivedDataPath "$XCODE_DERIVED_DATA_PATH" | xcpretty
      after_success:
        - bash <(curl -s https://codecov.io/bash) -D $XCODE_DERIVED_DATA_PATH -J "^$XCODE_SCHEME$"
    - stage: Pod lib lint
      script: 
        - pod repo update --silent
        - pod lib lint --verbose
    - stage: Deploy Github
      script: skip
      before_deploy:
        - carthage build --no-skip-current --cache-builds
        - carthage archive Alicerce
      deploy:
        - provider: releases
          api_key: $GITHUB_OAUTH_TOKEN
          file: Alicerce.framework.zip
          skip_cleanup: true
          overwrite: true
          on:
            repo: Mindera/Alicerce
            branch: master
            tags: true
    - stage: Deploy Cocoapods
      script: skip
      deploy:
        - provider: script
          script: pod trunk push
          skip_cleanup: true
          on:
            repo: Mindera/Alicerce
            branch: master
            tags: true
