language: swift
osx_image: xcode8.3
before_install: true
install: true
xcode_project: Alicerce.xcodeproj
env:
  global:
    - XCODE_PROJECT_NAME=Alicerce
    - XCODE_SDK=iphonesimulator
    - XCODE_ACTION='build test'
    - XCODE_DESTINATION='platform=iOS Simulator,name=iPhone 6s,OS=10.3'
    - XCODE_DERIVED_DATA_PATH=build
  matrix:
    - XCODE_SCHEME=Alicerce
script:
  - set -o pipefail
  - xcodebuild $XCODE_ACTION -project "$TRAVIS_XCODE_PROJECT" -scheme "$XCODE_SCHEME" -sdk "$XCODE_SDK" -destination "$XCODE_DESTINATION" -derivedDataPath "$XCODE_DERIVED_DATA_PATH"
after_success:
  - bash <(curl -s https://codecov.io/bash) -D $XCODE_DERIVED_DATA_PATH
notifications:
  email: false