name: Danger

on:

  pull_request:
    branches:
      - master
      
jobs:

  Danger:
    name: Danger Swift
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Danger
        uses: 417-72KI/danger-swiftlint@v5.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
