name: Danger-CI
on: pull_request
jobs:
build:
runs-on: macos-latest

steps:
- uses: actions/checkout@master
- name: Build
run: swift build

- name: Test
run: swift test

- name: Danger
run: danger-swift ci
env: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
