name: CocoaPods Lint

on:
  push:
    branches:
      - master
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'
  pull_request:
    branches:
      - master

env:
  # https://github.com/actions/virtual-environments/tree/main/images/macos
  DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer

jobs:
  main:
    name: Pod Lint
    runs-on: macOS-10.15
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: ruby versions
        run: |
          ruby --version
          gem --version
          bundler --version

      - name: cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gem-

      - name: bundle install
        run: |
          gem install bundler --no-document
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: pod lint
        run: bundle exec pod lib lint
